name: 'Octostache wrapper Action'
description: 'A Github action to replicate the octopus variable substitution feature'
branding:
  icon: hash
  color: purple
inputs:
  variables-file:
    description: An optional yaml file containing variables to use in the substitution.
    required: false
  files-with-substitutions:
    description: 'A comma separated list of files with #{variables} that need substitution.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --variables-file="${{ inputs.variables-file }}"
    - --files-with-substitutions="${{ inputs.files-with-substitutions }}"
