name: 'Octostache wrapper Action'
description: 'A Github action to replicate the octopus variable substitution feature'
branding:
  icon: hash
  color: purple
inputs:
  variables-file:
    description: An optional yaml file containing variables to use in the substitution.
    required: false
  files-with-substitutions:
    description: A comma separated list of files that contains the octo tokens needing to be substituted.
    required: true
  output-files:
    description: |
      An optional comma separated list of files to output.
      If defined, the program assumes the index of the output file is the same as the index of the template file in the template-files list. They therefore need to have the same number of elements.
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --variable-file="${{ inputs.variables-file }}"
    - --template-files="${{ inputs.files-with-substitutions }}"
    - --output-files="${{ inputs.output-files }}"
